export const dataCategories = [
    "Action",
    "Adventure",
    "Animation",
    "Biographical",
    "Comedy",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Gaming",
    "Historical",
    "Horror",
    "Musical",
    "Mystery",
    "News",
    "Reality TV",
    "Romance",
    "Science Fiction",
    "Sports",
    "Talk Show",
    "Thriller",
    "War",
    "Western",
];
